apiVersion: v1
kind: Secret
metadata:
  name: zorua-config
  labels:
    app: zorua
stringData:
  config.json: '
  {
    "Domain": {{ required "A valid .Values.domain must be specified!" .Values.domain | quote }},
    "Credentials": {
      "Username": {{ required "A valid .Values.credentials.username must be specified!" .Values.credentials.username | quote }},
      "Password": {{ required "A valid .Values.credentials.password must be specified!" .Values.credentials.password | quote }}
    }
  }
  '
